# Generated by Django 5.1.6 on 2025-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="instruments",
            field=models.ManyToManyField(blank=True, to="panel.instrument"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="force_opens",
            field=models.ManyToManyField(
                blank=True, related_name="force_open_strategies", to="panel.instrument"
            ),
        ),
    ]
